# Generated by Django 2.2.1 on 2019-05-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='お名前')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('sex', models.IntegerField(choices=[(1, '男性'), (2, '女性')], default=1, verbose_name='性別')),
                ('job', models.IntegerField(choices=[(1, '会社員'), (2, 'フリーター'), (3, '学生')], verbose_name='職業')),
                ('inquiry_text', models.TextField(max_length=500, verbose_name='問い合わせ内容')),
            ],
        ),
    ]
